
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 81
#define YY_END_OF_BUFFER 82
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[517] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   82,   81,   71,   72,   81,   73,
       76,   80,   80,   75,   74,   77,   78,   79,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,    2,    2,    2,    4,    4,    4,   74,
       80,   80,   42,   80,   80,   43,   49,   49,   49,   62,
       62,   62,   81,    6,    6,    6,   81,   71,    0,   70,
       73,   80,   74,   80,   74,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,

       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   17,    2,    2,    2,    2,    4,    4,
        4,    4,    8,    8,   42,   80,   42,   41,   40,   49,
       49,   49,   49,   62,   62,   62,   62,    0,   66,    6,
        6,    6,    6,    0,   69,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   53,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   52,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,    7,   80,   80,    3,   80,   80,   80,   80,   80,

       80,   80,   80,   80,   80,   80,   80,   80,    5,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   15,
       80,   80,   80,   80,   80,   80,   80,   38,   80,   80,
       80,   80,   80,   80,   80,   22,   21,   80,   80,   80,
       80,   80,   64,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   16,   80,   63,   80,   80,   80,   80,
       80,   80,   80,   80,    8,   80,   80,   80,   80,   80,
       80,   80,   80,   67,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   19,   80,
       10,   80,   80,   80,   80,   80,   12,   65,   80,   45,

       80,   80,   59,    9,   80,   80,   80,   54,   80,   80,
       58,   80,   68,   80,   80,   80,   61,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   14,
       80,   46,   57,   80,   80,   80,   80,   80,   80,   56,
       39,   47,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   50,   80,   55,   80,   80,   80,   51,   80,
       80,   80,   80,   80,    1,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   13,
       80,   80,   80,   80,   80,   80,   80,   80,   11,   80,
       80,   80,   80,   80,   80,   80,   24,   80,   60,   80,

       80,   80,   80,   27,   80,   80,   34,   80,   18,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   20,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   48,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   29,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   37,   80,   80,   31,   80,
       80,   44,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   28,   80,   80,   80,
       25,   80,   80,   80,   23,   80,   30,   80,   80,   32,

       80,   80,   80,   80,   80,   80,   80,   80,   80,   35,
       80,   26,   80,   36,   33,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    1,    1,
        1,    1,    1,    6,    7,    8,    9,   10,   10,   10,
       10,   10,   11,   10,   10,   10,   10,   12,   13,    1,
        1,    1,    1,    1,   14,   15,   16,   17,   15,   15,
       18,   19,   18,   18,   18,   18,   20,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
        1,    1,    1,    1,   18,    1,   21,   22,   23,   24,

       25,   26,   27,   28,   29,   18,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       44,   18,   45,    1,   46,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[47] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    3,    1,    3,
        3,    3,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    1,    1
    } ;

static yyconst flex_int16_t yy_base[533] =
    {   0,
        0,   46,   74,    0,  113,  159,    0,    0,  205,  251,
      288,    0,    8,   25,  314,  360,  406,  452,  767,  766,
      498,  544,  765,  764,  767,  772,  764,  772,  761,    0,
      772,    0,    4,  772,   12,  772,  772,  772,  744,    0,
      740,    4,  719,    0,    4,  736,  726,   32,  724,    5,
       41,   44,  724,    0,   16,   66,    0,   53,   70,  583,
       74,   76,  117,  736,  732,  772,    0,   78,  121,    0,
       90,  125,  751,    0,  127,  131,  750,  751,  748,  772,
        0,    0,  133,  135,  139,  737,  726,   41,  710,  716,
      716,  714,  716,  709,  722,  704,  734,  733,   71,  695,

      705,  699,  701,  696,  700,  123,  118,  701,  150,  695,
       97,  696,  709,    0,    0,  144,  164,  169,    0,  171,
      173,  177,  181,  717,  184,  186,  190,    0,    0,    0,
      192,  209,  213,    0,  215,  217,  221,  724,  772,    0,
      223,  225,  229,  723,  772,  710,  688,  690,  689,  694,
      698,  699,  698,  694,  688,  693,  676,  208,  693,  682,
      183,  687,  682,  676,  223,  702,  679,  676,  680,  666,
      677,  674,    0,  671,  667,  663,  659,  669,  660,  672,
      688,  687,  600,   10,  668,  655,  649,  665,  651,  644,
      658,    0,  649,  215,    0,  664,  660,  645,  642,  648,

      643,  642,  166,  655,  128,  670,  638,  641,    0,   54,
      640,  641,  613,  604,  602,  605,  604,  585,  594,    0,
      580,  213,  617,  593,  595,  565,  573,    0,  568,  589,
      570,  559,  563,  555,  562,    0,    0,  547,  560,  554,
      550,  555,    0,  554,  545,  544,  552,  225,  551,  542,
      537,  530,  549,    0,  564,    0,  544,  531,  530,  528,
      527,  540,  540,  538,  550,  544,  549,  521,  519,  517,
      513,  518,  534,    0,  516,  528,  504,  512,  497,  514,
      513,  499,  492,  499,  493,  495,  503,  490,    0,  501,
      518,  490,  500,  493,  493,  481,    0,    0,  482,    0,

      485,  506,    0,  509,  487,  485,  488,  482,  477,  494,
        0,  473,    0,  451,  455,  470,    0,  459,  470,  449,
      457,  451,  446,  453,  456,  453,  449,  455,  442,    0,
      439,    0,    0,  444,  446,  454,  439,  450,  453,    0,
        0,    0,  444,  447,  432,  441,  444,  447,  426,  441,
      441,  426,    0,  418,    0,  420,  423,  413,    0,  425,
      404,  400,  411,  408,    0,  416,  407,  402,  409,  412,
      399,  410,  395,  401,  400,  394,  396,  390,  403,    0,
      402,  393,  388,  417,  416,  389,  384,  382,    0,  393,
      384,  379,  396,  371,  372,  363,  392,  391,    0,  364,

      224,  389,  388,    0,  357,  354,    0,  244,    0,  358,
      384,  352,  355,  367,  363,  352,  352,  245,  358,    0,
      359,  348,  348,  246,  355,  346,  346,  353,  344,  354,
      350,  338,  346,  334,  325,    0,  332,  321,  317,  322,
      327,  314,  329,  317,  324,  315,  323,  308,  323,  319,
      310,  300,  296,    0,  314,  309,  312,  299,  314,  309,
      308,  303,  294,  309,  304,    0,  290,  293,    0,  296,
      279,    0,  269,  273,  276,  271,  258,  256,  286,  254,
      258,  252,  282,  250,  254,  248,    0,  252,  246,  276,
        0,  249,  243,  273,    0,  258,    0,  245,  256,    0,

      243,  243,  253,  241,  251,  246,  214,  213,  146,    0,
      131,    0,  115,    0,    0,  772,  643,  646,  649,  652,
      655,  658,  661,  664,  131,  102,   87,   18,    9,  667,
        4,  670
    } ;

static yyconst flex_int16_t yy_def[533] =
    {   0,
      517,  517,    2,    3,  518,  518,    2,    2,  519,  519,
        2,   11,    2,    2,  520,  520,  521,  521,    2,    2,
      522,  522,    2,    2,  516,  516,  516,  516,  523,  524,
      516,  525,  525,  516,  525,  516,  516,  516,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  526,  526,  526,  527,  527,  527,  525,
       60,  525,  525,  525,  525,  516,  528,  528,  528,  529,
      529,  529,  530,  531,  531,  531,  532,  516,  523,  516,
      524,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,

      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  526,  526,  526,  526,  527,  527,
      527,  527,  525,  525,  525,  525,  525,  525,  525,  528,
      528,  528,  528,  529,  529,  529,  529,  530,  516,  531,
      531,  531,  531,  532,  516,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,

      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,

      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,

      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,

      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,    0,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516
    } ;

static yyconst flex_int16_t yy_nxt[819] =
    {   0,
       26,   27,   28,   29,   30,   31,  140,   33,   34,   35,
       35,  134,   36,   83,   83,   62,  224,   63,   63,   84,
      130,   85,   85,   87,   97,  116,  116,   98,   91,  225,
       88,   95,   62,   96,   63,   63,   99,   92,  105,   89,
       64,  106,   65,   93,   37,   38,   26,   27,   28,   29,
       30,   31,   66,   33,   34,   35,   35,   64,   36,   65,
      102,  107,  120,  120,  108,  109,  110,  148,  111,   66,
      103,  149,  112,  117,  113,  118,  118,  121,  251,  122,
      122,   82,  252,  124,  124,  125,  125,  131,  131,  119,
       37,   38,   39,  160,   40,   41,  161,   42,   43,  135,

      135,   44,   45,   46,  115,   47,   48,   49,   50,  162,
       51,   52,   53,   26,   27,   28,   29,   30,   31,  179,
       55,   34,   56,   56,  126,   36,  127,  127,  132,  180,
      133,  133,  136,   82,  137,  137,  141,  141,  142,  515,
      143,  143,   83,   83,   83,   83,   84,  169,   85,   85,
      171,  246,  172,  116,  116,  514,  170,   37,   38,   26,
       27,   28,   29,   30,   31,  247,   55,   34,   56,   56,
      174,   36,  175,  116,  116,  176,  117,  513,  118,  118,
      120,  120,  120,  120,  121,  177,  122,  122,   84,  243,
       85,   85,  183,  125,  125,  125,  125,  126,  244,  127,

      127,  131,  131,   37,   38,   26,   27,   28,   29,   30,
       31,  200,   58,   34,   59,   59,  201,   36,  131,  131,
      132,  234,  133,  133,  135,  135,  135,  135,  136,  205,
      137,  137,  141,  141,  141,  141,  142,  512,  143,  143,
      196,  263,  197,  264,  415,  511,  235,  416,  286,   37,
       38,   26,   27,   28,   29,   30,   31,  206,   58,   34,
       59,   59,  287,   36,  421,  431,  437,  422,  432,  438,
      510,  509,  508,  507,  506,  505,  504,  503,  502,  501,
      500,  499,  498,  497,  496,  495,  494,  493,  492,  491,
      490,  489,  488,  487,  486,   37,   38,   60,   60,  485,

      484,   61,   61,   61,   61,  483,  482,  481,   61,   61,
       61,   61,   61,   61,   26,   27,   28,   29,   30,   31,
      480,   68,   34,   69,   69,  479,   36,  478,  477,  476,
      475,  474,  473,  472,  471,  470,  469,  468,  467,  466,
      465,  464,  463,  462,  461,  460,  459,  458,  457,  456,
      455,  454,  453,  452,  451,  450,  449,  448,   37,   38,
       26,   27,   28,   29,   30,   31,  447,   68,   34,   69,
       69,  446,   36,  445,  444,  443,  442,  441,  440,  439,
      436,  435,  434,  433,  430,  429,  428,  427,  426,  425,
      424,  423,  420,  419,  418,  417,  414,  413,  412,  411,

      410,  409,  408,  407,   37,   38,   26,   27,   28,   29,
       30,   31,  406,   71,   34,   72,   72,  405,   36,  404,
      403,  402,  401,  400,  399,  398,  397,  396,  395,  394,
      393,  392,  391,  390,  389,  388,  387,  386,  385,  384,
      383,  382,  381,  380,  379,  378,  377,  376,  375,  374,
       37,   38,   26,   27,   28,   29,   30,   31,  373,   71,
       34,   72,   72,  372,   36,  371,  370,  369,  368,  367,
      366,  365,  364,  363,  362,  361,  360,  359,  358,  357,
      356,  355,  354,  353,  352,  351,  350,  349,  348,  347,
      346,  345,  344,  343,  342,  341,   37,   38,   26,   27,

       28,   29,   30,   31,  340,   75,   34,   76,   76,  339,
       36,  338,  337,  336,  335,  334,  333,  332,  331,  330,
      329,  328,  327,  326,  325,  324,  323,  322,  321,  320,
      319,  318,  317,  316,  315,  314,  313,  312,  311,  310,
      309,  308,   37,   38,   26,   27,   28,   29,   30,   31,
      307,   75,   34,   76,   76,  306,   36,  305,  304,  303,
      302,  183,  301,  300,  299,  298,  297,  296,  295,  294,
      293,  292,  291,  290,  289,  288,  285,  284,  283,  282,
      281,  280,  279,  278,  277,  276,  275,  274,   37,   38,
       84,  273,  123,  123,  272,  271,  124,  124,  124,  124,

      270,  269,  268,  124,  124,  124,  124,  124,  124,  223,
      223,  267,  266,  223,  223,  223,  223,  262,  261,  260,
      223,  223,  223,  223,  223,  223,  265,  265,  259,  258,
      265,  265,  265,  265,  257,  256,  255,  265,  265,  265,
      265,  265,  265,   32,   32,   32,   54,   54,   54,   57,
       57,   57,   67,   67,   67,   70,   70,   70,   74,   74,
       74,   79,   79,   79,   81,  254,   81,  138,  138,  138,
      144,  144,  144,  253,  250,  249,  248,  245,  242,  241,
      240,  239,  238,  237,  236,  233,  232,  231,  230,  229,
      228,  227,  226,  222,  221,  220,  219,  218,  217,  216,

      215,  214,  213,  212,  211,  210,  209,  208,  207,  204,
      203,  202,  199,  198,  195,  194,  193,  192,  191,  190,
      189,  188,  187,  186,  185,  184,  145,  139,  183,  182,
      181,  178,  173,  168,  167,  166,  165,  164,  163,  159,
      158,  157,  156,  155,  154,  153,  152,  151,  150,  147,
      146,   80,   78,  145,  139,  129,  128,  114,  104,  101,
      100,   94,   90,   86,   80,   78,  516,   77,   77,   73,
       73,   25,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,

      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516
    } ;

static yyconst flex_int16_t yy_chk[819] =
    {   0,
        1,    1,    1,    1,    1,    1,  531,    1,    1,    1,
        1,  529,    1,   33,   33,   13,  184,   13,   13,   35,
      528,   35,   35,   40,   45,   55,   55,   45,   42,  184,
       40,   44,   14,   44,   14,   14,   45,   42,   50,   40,
       13,   50,   13,   42,    1,    1,    2,    2,    2,    2,
        2,    2,   13,    2,    2,    2,    2,   14,    2,   14,
       48,   51,   58,   58,   51,   51,   52,   88,   52,   14,
       48,   88,   52,   56,   52,   56,   56,   59,  210,   59,
       59,   61,  210,   61,   61,   62,   62,   68,   68,  527,
        2,    2,    3,   99,    3,    3,   99,    3,    3,   71,

       71,    3,    3,    3,  526,    3,    3,    3,    3,   99,
        3,    3,    3,    5,    5,    5,    5,    5,    5,  111,
        5,    5,    5,    5,   63,    5,   63,   63,   69,  111,
       69,   69,   72,  525,   72,   72,   75,   75,   76,  513,
       76,   76,   83,   83,   84,   84,   85,  106,   85,   85,
      107,  205,  107,  116,  116,  511,  106,    5,    5,    6,
        6,    6,    6,    6,    6,  205,    6,    6,    6,    6,
      109,    6,  109,  117,  117,  109,  118,  509,  118,  118,
      120,  120,  121,  121,  122,  109,  122,  122,  123,  203,
      123,  123,  123,  125,  125,  126,  126,  127,  203,  127,

      127,  131,  131,    6,    6,    9,    9,    9,    9,    9,
        9,  161,    9,    9,    9,    9,  161,    9,  132,  132,
      133,  194,  133,  133,  135,  135,  136,  136,  137,  165,
      137,  137,  141,  141,  142,  142,  143,  508,  143,  143,
      158,  222,  158,  222,  401,  507,  194,  401,  248,    9,
        9,   10,   10,   10,   10,   10,   10,  165,   10,   10,
       10,   10,  248,   10,  408,  418,  424,  408,  418,  424,
      506,  505,  504,  503,  502,  501,  499,  498,  496,  494,
      493,  492,  490,  489,  488,  486,  485,  484,  483,  482,
      481,  480,  479,  478,  477,   10,   10,   11,   11,  476,

      475,   11,   11,   11,   11,  474,  473,  471,   11,   11,
       11,   11,   11,   11,   15,   15,   15,   15,   15,   15,
      470,   15,   15,   15,   15,  468,   15,  467,  465,  464,
      463,  462,  461,  460,  459,  458,  457,  456,  455,  453,
      452,  451,  450,  449,  448,  447,  446,  445,  444,  443,
      442,  441,  440,  439,  438,  437,  435,  434,   15,   15,
       16,   16,   16,   16,   16,   16,  433,   16,   16,   16,
       16,  432,   16,  431,  430,  429,  428,  427,  426,  425,
      423,  422,  421,  419,  417,  416,  415,  414,  413,  412,
      411,  410,  406,  405,  403,  402,  400,  398,  397,  396,

      395,  394,  393,  392,   16,   16,   17,   17,   17,   17,
       17,   17,  391,   17,   17,   17,   17,  390,   17,  388,
      387,  386,  385,  384,  383,  382,  381,  379,  378,  377,
      376,  375,  374,  373,  372,  371,  370,  369,  368,  367,
      366,  364,  363,  362,  361,  360,  358,  357,  356,  354,
       17,   17,   18,   18,   18,   18,   18,   18,  352,   18,
       18,   18,   18,  351,   18,  350,  349,  348,  347,  346,
      345,  344,  343,  339,  338,  337,  336,  335,  334,  331,
      329,  328,  327,  326,  325,  324,  323,  322,  321,  320,
      319,  318,  316,  315,  314,  312,   18,   18,   21,   21,

       21,   21,   21,   21,  310,   21,   21,   21,   21,  309,
       21,  308,  307,  306,  305,  304,  302,  301,  299,  296,
      295,  294,  293,  292,  291,  290,  288,  287,  286,  285,
      284,  283,  282,  281,  280,  279,  278,  277,  276,  275,
      273,  272,   21,   21,   22,   22,   22,   22,   22,   22,
      271,   22,   22,   22,   22,  270,   22,  269,  268,  267,
      266,  265,  264,  263,  262,  261,  260,  259,  258,  257,
      255,  253,  252,  251,  250,  249,  247,  246,  245,  244,
      242,  241,  240,  239,  238,  235,  234,  233,   22,   22,
       60,  232,   60,   60,  231,  230,   60,   60,   60,   60,

      229,  227,  226,   60,   60,   60,   60,   60,   60,  183,
      183,  225,  224,  183,  183,  183,  183,  221,  219,  218,
      183,  183,  183,  183,  183,  183,  223,  223,  217,  216,
      223,  223,  223,  223,  215,  214,  213,  223,  223,  223,
      223,  223,  223,  517,  517,  517,  518,  518,  518,  519,
      519,  519,  520,  520,  520,  521,  521,  521,  522,  522,
      522,  523,  523,  523,  524,  212,  524,  530,  530,  530,
      532,  532,  532,  211,  208,  207,  206,  204,  202,  201,
      200,  199,  198,  197,  196,  193,  191,  190,  189,  188,
      187,  186,  185,  182,  181,  180,  179,  178,  177,  176,

      175,  174,  172,  171,  170,  169,  168,  167,  166,  164,
      163,  162,  160,  159,  157,  156,  155,  154,  153,  152,
      151,  150,  149,  148,  147,  146,  144,  138,  124,  113,
      112,  110,  108,  105,  104,  103,  102,  101,  100,   98,
       97,   96,   95,   94,   93,   92,   91,   90,   89,   87,
       86,   79,   78,   77,   73,   65,   64,   53,   49,   47,
       46,   43,   41,   39,   29,   27,   25,   24,   23,   20,
       19,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,

      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "cftoken.l"
/*	$KAME: cftoken.l,v 1.35 2005/01/12 06:06:11 suz Exp $	*/
#line 5 "cftoken.l"
/*
 * Copyright (C) 2002 WIDE Project.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the project nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE PROJECT AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE PROJECT OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */
#include <sys/types.h>
#include <sys/param.h>
#include <sys/socket.h>
#include <sys/queue.h>
#include <sys/time.h>

#include <netinet/in.h>

#include <errno.h>
#include <syslog.h>
#include <string.h>
#ifdef HAVE_STDARG_H
#include <stdarg.h>
#else
#include <varargs.h>
#endif

#include "dhcp6.h"
#include "config.h"
#include "common.h"
#include "y.tab.h"

#define YY_NO_UNPUT 1

char *configfilename;
int lineno = 1;


/* Recursion limit for includes */
#define MAX_INCLUDE_DEPTH 10

static struct include_stack {
	char *path;
	YY_BUFFER_STATE state;
	int lineno;
} incstack[MAX_INCLUDE_DEPTH];
int incstackp = 0;


static int yy_first_time = 1;
static int yyerrorcount = 0;
 
#ifndef NOCONFIG_DEBUG
#define YYDEBUG 1

int cfdebug = 1;
#else
int cfdebug = 0;
#endif

extern int yyparse __P((void));
extern int cf_post_config __P((void));

static void cfdebug_print __P((char *, char *, int));

#define DP(str) if (cfdebug) cfdebug_print(str, yytext, yyleng)
#define DECHO if (cfdebug) cfdebug_print(NULL, yytext, yyleng);
#define DNOECHO if (cfdebug) cfdebug_print(NULL, "****", yyleng);
/* abbreviations */











#line 915 "lex.yy.c"

#define INITIAL 0
#define S_CNF 1
#define S_IFACE 2
#define S_PREF 3
#define S_HOST 4
#define S_DUID 5
#define S_IA 6
#define S_AUTH 7
#define S_KEY 8
#define S_SECRET 9
#define S_ADDRPOOL 10
#define S_INCL 11

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 125 "cftoken.l"


	if (yy_first_time) {
		BEGIN S_CNF;
		yy_first_time = 0;
	}

	/* interface configuration */
#line 1122 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 517 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 772 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 133 "cftoken.l"
{ DECHO; BEGIN S_IFACE; return (INTERFACE); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 134 "cftoken.l"
{
	DECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (IFNAME);
}
	YY_BREAK
/* host configuration */
case 3:
YY_RULE_SETUP
#line 142 "cftoken.l"
{ DECHO; BEGIN S_HOST; return (HOST); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 143 "cftoken.l"
{
	DECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (HOSTNAME);
}
	YY_BREAK
/* address pool configuration */
case 5:
YY_RULE_SETUP
#line 151 "cftoken.l"
{ DECHO; BEGIN S_ADDRPOOL; return (ADDRPOOL); }  
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 153 "cftoken.l"
{
	DECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (POOLNAME);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 160 "cftoken.l"
{ DECHO; BEGIN S_DUID; return (DUID); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 161 "cftoken.l"
{
	DECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (DUID_ID);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 168 "cftoken.l"
{ DECHO; return (ADDRESS); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 170 "cftoken.l"
{ DECHO; return (PREFIX); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 172 "cftoken.l"
{ DECHO; return (PREFERENCE); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 174 "cftoken.l"
{ DECHO; return (SCRIPT); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 176 "cftoken.l"
{ DECHO; return (DELAYEDKEY); }
	YY_BREAK
/* request */
case 14:
YY_RULE_SETUP
#line 179 "cftoken.l"
{ DECHO; return (REQUEST); }
	YY_BREAK
/* send */
case 15:
YY_RULE_SETUP
#line 182 "cftoken.l"
{ DECHO; return (SEND); }
	YY_BREAK
/* range */
case 16:
YY_RULE_SETUP
#line 185 "cftoken.l"
{ DECHO; return (RANGE); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 186 "cftoken.l"
{ DECHO; return (TO); }
	YY_BREAK
/* address-pool */
case 18:
YY_RULE_SETUP
#line 189 "cftoken.l"
{ DECHO; return (ADDRESS_POOL); }
	YY_BREAK
/* DHCP options */
case 19:
YY_RULE_SETUP
#line 192 "cftoken.l"
{ DECHO; return (OPTION); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 194 "cftoken.l"
{ DECHO; return (RAPID_COMMIT); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 195 "cftoken.l"
{ DECHO; return (IA_PD); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 196 "cftoken.l"
{ DECHO; return (IA_NA); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 197 "cftoken.l"
{ DECHO; return (DNS_SERVERS); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 198 "cftoken.l"
{ DECHO; return (DNS_NAME); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 199 "cftoken.l"
{ DECHO; return (SIP_SERVERS); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 200 "cftoken.l"
{ DECHO; return (SIP_NAME); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 201 "cftoken.l"
{ DECHO; return (NTP_SERVERS); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 202 "cftoken.l"
{ DECHO; return (NIS_SERVERS); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 203 "cftoken.l"
{ DECHO; return (NIS_NAME); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 204 "cftoken.l"
{ DECHO; return (NISP_SERVERS); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 205 "cftoken.l"
{ DECHO; return (NISP_NAME); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 206 "cftoken.l"
{ DECHO; return (BCMCS_SERVERS); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 207 "cftoken.l"
{ DECHO; return (BCMCS_NAME); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 208 "cftoken.l"
{ DECHO; return (REFRESHTIME); }
	YY_BREAK
/* provided for a backward compatibility to WIDE-DHCPv6 before Oct 1 2006 */
case 35:
YY_RULE_SETUP
#line 211 "cftoken.l"
{ DECHO; return (NIS_NAME); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 212 "cftoken.l"
{ DECHO; return (NISP_NAME); }	
	YY_BREAK
/* generic options */
case 37:
YY_RULE_SETUP
#line 215 "cftoken.l"
{ DECHO; return (INFO_ONLY); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 217 "cftoken.l"
{ DECHO; return (ALLOW); }
	YY_BREAK
/* identity association */
case 39:
YY_RULE_SETUP
#line 220 "cftoken.l"
{ DECHO; BEGIN S_IA; return(ID_ASSOC); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 221 "cftoken.l"
{ DECHO; return(IA_PD); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 222 "cftoken.l"
{ DECHO; return(IA_NA); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 223 "cftoken.l"
{ DECHO; yylval.str = strdup(yytext); return(IAID); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 224 "cftoken.l"
{ DP("begin of closure"); BEGIN S_CNF; return (BCL); }
	YY_BREAK
/*
	 * interface parameters for delegated prefix configuration.
	 * when lex reads an interface name, the state will be back to
	 * S_CNF.
	 */
case 44:
YY_RULE_SETUP
#line 231 "cftoken.l"
{ DECHO; BEGIN S_IFACE; return (PREFIX_INTERFACE); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 232 "cftoken.l"
{ DECHO; return (SLA_ID); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 233 "cftoken.l"
{ DECHO; return (SLA_LEN); }
	YY_BREAK
/* duration */
case 47:
YY_RULE_SETUP
#line 236 "cftoken.l"
{ DECHO; return (INFINITY); }
	YY_BREAK
/* authentication option */
case 48:
YY_RULE_SETUP
#line 239 "cftoken.l"
{ DECHO; BEGIN S_AUTH; return (AUTHENTICATION); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 240 "cftoken.l"
{
	DECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (AUTHNAME);
}
	YY_BREAK
/* authentication parameters */
case 50:
YY_RULE_SETUP
#line 248 "cftoken.l"
{ DECHO; return (PROTOCOL); };
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 249 "cftoken.l"
{ DECHO; return (ALGORITHM); };
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 250 "cftoken.l"
{ DECHO; return (RDM); };
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 251 "cftoken.l"
{ DECHO; return (KEY); };
	YY_BREAK
/* authentication protocols */
case 54:
YY_RULE_SETUP
#line 254 "cftoken.l"
{ DECHO; return (DELAYED); };
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 255 "cftoken.l"
{ DECHO; return (RECONFIG); };
	YY_BREAK
/* authentication algorithms */
case 56:
YY_RULE_SETUP
#line 258 "cftoken.l"
{ DECHO; return (HMACMD5); };
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 259 "cftoken.l"
{ DECHO; return (HMACMD5); };
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 260 "cftoken.l"
{ DECHO; return (HMACMD5); };
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 261 "cftoken.l"
{ DECHO; return (HMACMD5); };
	YY_BREAK
/* authentication RDM */
case 60:
YY_RULE_SETUP
#line 264 "cftoken.l"
{ DECHO; return (MONOCOUNTER); };
	YY_BREAK
/* secret keys */
case 61:
YY_RULE_SETUP
#line 267 "cftoken.l"
{ DECHO; BEGIN S_KEY; return (KEYINFO); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 268 "cftoken.l"
{
	DECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (KEYNAME);
}
	YY_BREAK
/* key parameters */
case 63:
YY_RULE_SETUP
#line 276 "cftoken.l"
{ DECHO; return (REALM); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 277 "cftoken.l"
{ DECHO; return (KEYID); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 278 "cftoken.l"
{ DECHO; BEGIN S_SECRET; return (SECRET); }
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 279 "cftoken.l"
{
	DNOECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (QSTRING);
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 285 "cftoken.l"
{ DECHO; return (EXPIRE); }
	YY_BREAK
/* include */
case 68:
YY_RULE_SETUP
#line 288 "cftoken.l"
{ DECHO; BEGIN S_INCL; return (INCLUDE); }
	YY_BREAK
case 69:
/* rule 69 can match eol */
YY_RULE_SETUP
#line 289 "cftoken.l"
{
	DECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (QSTRING);
}
	YY_BREAK
/* quoted string */
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 297 "cftoken.l"
{
		DECHO;
		yylval.str = strdup(yytext);
		return (QSTRING);
	}
	YY_BREAK
/* misc */
case 71:
YY_RULE_SETUP
#line 304 "cftoken.l"
{ ; }
	YY_BREAK
case 72:
/* rule 72 can match eol */
YY_RULE_SETUP
#line 305 "cftoken.l"
{ lineno++; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 306 "cftoken.l"
{ DP("comment"); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 307 "cftoken.l"
{
	DECHO;
	yylval.num = strtoll(yytext, NULL, 10);
	return (NUMBER);
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 312 "cftoken.l"
{ DECHO; return (SLASH); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 313 "cftoken.l"
{ DECHO; return (COMMA); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 314 "cftoken.l"
{ DP("end of sentence"); return (EOS); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 315 "cftoken.l"
{ DP("begin of closure"); return (BCL); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 316 "cftoken.l"
{ DP("end of closure"); return (ECL); }
	YY_BREAK
/* generic string */
case 80:
YY_RULE_SETUP
#line 319 "cftoken.l"
{
		DECHO;
		yylval.str = strdup(yytext);
		return (STRING);
	}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(S_CNF):
case YY_STATE_EOF(S_IFACE):
case YY_STATE_EOF(S_PREF):
case YY_STATE_EOF(S_HOST):
case YY_STATE_EOF(S_DUID):
case YY_STATE_EOF(S_IA):
case YY_STATE_EOF(S_AUTH):
case YY_STATE_EOF(S_KEY):
case YY_STATE_EOF(S_SECRET):
case YY_STATE_EOF(S_ADDRPOOL):
case YY_STATE_EOF(S_INCL):
#line 325 "cftoken.l"
{
		if (--incstackp < 0)
			yyterminate();
		else {
			yy_delete_buffer(YY_CURRENT_BUFFER);
			free(incstack[incstackp + 1].path);
			configfilename = incstack[incstackp].path;
			lineno = incstack[incstackp].lineno;
			yy_switch_to_buffer(incstack[incstackp].state);
		}
	}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 337 "cftoken.l"
ECHO;
	YY_BREAK
#line 1718 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 517 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 517 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 516);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 337 "cftoken.l"


static void
cfdebug_print(w, t, l)
	char *w, *t;
	int l;
{
	if (w) {
		dprintf(LOG_DEBUG, FNAME,
		    "<%d>%s [%s] (%d)", yy_start, w, t, l);
	} else {
		dprintf(LOG_DEBUG, FNAME,
		    "<%d>[%s] (%d)", yy_start, t, l);
	}
}

static void
yyerror0(int level, char *s, va_list ap)
{
	char ebuf[BUFSIZ], *bp, *ep;

	bp = ebuf;
	ep = ebuf + sizeof(ebuf);
	bp += snprintf(bp, ep - bp, "%s %d: ", configfilename, lineno);
	if (bp < ep)
		bp += vsnprintf(bp, ep - bp, s, ap);

	dprintf(level, FNAME, ebuf);
}

void
yyerror(char *s, ...)
{
	va_list ap;
#ifdef HAVE_STDARG_H
	va_start(ap, s);
#else
	va_start(ap);
#endif
	yyerror0(LOG_ERR, s, ap);
	va_end(ap);
	yyerrorcount++;
}

void
yywarn(char *s, ...)
{
	va_list ap;
#ifdef HAVE_STDARG_H
	va_start(ap, s);
#else
	va_start(ap);
#endif
	yyerror0(LOG_WARNING, s, ap);
	va_end(ap);
}

int
cfswitch_buffer(incl)
	char *incl;
{
	char *path = qstrdup(incl);
	FILE *fp;

	if (incstackp >= MAX_INCLUDE_DEPTH) {
		dprintf(LOG_ERR, FNAME, "cfparse: includes nested too deeply");
		return (-1);
	}
	incstack[incstackp].path = configfilename;
	incstack[incstackp].state = YY_CURRENT_BUFFER;
	incstack[incstackp].lineno = lineno;

	fp = fopen(path, "r");
	if (fp == NULL) {
		dprintf(LOG_ERR, FNAME, "cfparse: fopen(%s): %s",
			path, strerror(errno));
		if (errno == ENOENT)
			return (0);
		return (-1);
	}
	incstackp++;
	configfilename = path;
	lineno = 1;
	yy_switch_to_buffer(yy_create_buffer(fp,YY_BUF_SIZE));

	BEGIN(S_CNF);

	return (0);
}

int
cfparse(conf)
	char *conf;
{
	configfilename = conf;
	if ((yyin = fopen(configfilename, "r")) == NULL) {
		dprintf(LOG_ERR, FNAME, "cfparse: fopen(%s): %s",
			configfilename, strerror(errno));
		if (errno == ENOENT)
			return (0);
		return (-1);
	}

	if (yyparse() || yyerrorcount) {
		if (yyerrorcount) {
			yyerror("fatal parse failure: exiting (%d errors)",
				yyerrorcount);
		} else
			yyerror("fatal parse failure: exiting");
		return (-1);
	}

	return (cf_post_config());
}

